#!/bin/bash
# Rwanda NCSA Compliance Auditor - Engine Startup Script
# Run each command in a separate terminal tab

PROJECT_DIR="/Users/moiseiradukunda/Documents/CMU/RESEARCH PROJECT/model-engine"

echo "========================================"
echo "Rwanda NCSA Compliance Auditor"
echo "Engine Startup Commands"
echo "========================================"
echo ""
echo "Run each command in a SEPARATE terminal tab:"
echo ""
echo "========================================"
echo "STEP 1: Start Redis (if using Docker)"
echo "========================================"
echo "docker run -d --name rwanda-redis -p 6379:6379 redis:7-alpine"
echo ""
echo "OR install Redis locally:"
echo "brew install redis && redis-server"
echo ""
echo "========================================"
echo "STEP 2: Start ENGINE 7 (Auth Engine)"
echo "========================================"
echo "cd \"$PROJECT_DIR\" && source venv/bin/activate && \\"
echo "  python -m uvicorn engines.engine7-auth-engine.app.main:app --host 0.0.0.0 --port 8007"
echo ""
echo "========================================"
echo "STEP 3: Start ENGINE 3 (XGBoost Classifier)"
echo "========================================"
echo "cd \"$PROJECT_DIR\" && source venv/bin/activate && \\"
echo "  python -m uvicorn engines.engine3-xgboost-classifier.app.main:app --host 0.0.0.0 --port 8003"
echo ""
echo "========================================"
echo "STEP 4: Start ENGINE 4 (Decision Engine)"
echo "========================================"
echo "cd \"$PROJECT_DIR\" && source venv/bin/activate && \\"
echo "  python -m uvicorn engines.engine4-decision-engine.app.main:app --host 0.0.0.0 --port 8004"
echo ""
echo "========================================"
echo "STEP 5: Start ENGINE 5 (Report Generator)"
echo "========================================"
echo "cd \"$PROJECT_DIR\" && source venv/bin/activate && \\"
echo "  python -m uvicorn engines.engine6-report-generator.app.main:app --host 0.0.0.0 --port 8005"
echo ""
echo "========================================"
echo "STEP 6: Start ENGINE 6 (Web UI)"
echo "========================================"
echo "cd \"$PROJECT_DIR\" && source venv/bin/activate && \\"
echo "  PYTHONPATH=\"\$PWD\" python -m uvicorn engines.engine5-web-ui.backend.api:socket_app --host 0.0.0.0 --port 8006"
echo ""
echo "========================================"
echo "STEP 7: Open Web UI in Browser"
echo "========================================"
echo "open http://localhost:8006"
echo ""
echo "========================================"
echo "STEP 8: Test API (in another terminal)"
echo "========================================"
echo "# Health checks:"
echo "curl http://localhost:8006/health"
echo "curl http://localhost:8007/health"
echo ""
echo "# Start an audit:"
echo "curl -X POST 'http://localhost:8006/api/v3/audits/start?target_host=localhost&framework=Rwanda-NCSA'"
echo ""
echo "# List audits:"
echo "curl http://localhost:8006/api/v3/audits"
echo ""
