#!/usr/bin/env python3
"""
Phase 1 — Clean XGBoost Retraining (v2)
Trains on leakage-free synthetic data (generated by generate_synthetic_data_v2.py).

Design:
  - Binary compliance classifier (compliant / non_compliant) per log entry
  - Explicitly EXCLUDES all leaky features: status_code, anomaly_label, severity
  - Features: TF-IDF(log_message, 50 terms) + 4 numeric + 13 one-hot control families
  - 5-fold stratified cross-validation
  - Per-family F1 reported for reviewer transparency

Outputs:
  models/xgboost_v2/xgboost_v2.pkl
  models/xgboost_v2/tfidf_vectorizer.pkl
  models/xgboost_v2/family_encoder.pkl
  models/xgboost_v2/model_metadata.json
  reports/xgboost_cv_summary.json
  reports/xgboost_per_family_f1.csv
  reports/xgboost_confusion_matrix.json
"""

import csv
import json
import math
import pickle
import time
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path

import numpy as np

ROOT = Path(__file__).parent.parent
DATA_DIR = ROOT / "data" / "synthetic"
MODEL_DIR = ROOT / "models" / "xgboost_v2"
REPORTS_DIR = ROOT / "reports"

MODEL_DIR.mkdir(parents=True, exist_ok=True)
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

# ──────────────────────────────────────────────────────────────────────────────
# FEATURES
# ──────────────────────────────────────────────────────────────────────────────
LEAKY_FEATURES = {"status_code", "anomaly_label", "severity", "control_id",
                  "control_name", "compliance_status", "event_id",
                  "timestamp", "user_id", "source_ip", "destination_ip",
                  "resource", "action", "log_message", "framework",
                  "control_family"}  # handled separately as categorical

NUMERIC_FEATURES = ["port", "hour_of_day", "day_of_week", "is_business_hours"]
TFIDF_MAX_FEATURES = 50
N_FOLDS = 5
RANDOM_SEED = 42


# ──────────────────────────────────────────────────────────────────────────────
# MINIMAL TF-IDF (no scipy dependency)
# ──────────────────────────────────────────────────────────────────────────────

class SimpleTfidf:
    def __init__(self, max_features=50, ngram_range=(1, 2), min_df=2):
        self.max_features = max_features
        self.ngram_range = ngram_range
        self.min_df = min_df
        self.vocab_: dict = {}
        self.idf_: dict = {}

    @staticmethod
    def _tokenize(text: str, ngram_range) -> list[str]:
        tokens = text.lower().split()
        tokens = [t for t in tokens if len(t) > 1 and not t.isdigit()]
        result = list(tokens)
        if ngram_range[1] >= 2:
            for i in range(len(tokens) - 1):
                result.append(f"{tokens[i]} {tokens[i+1]}")
        return result

    def fit(self, texts: list[str]):
        df_counter: Counter = Counter()
        n = len(texts)
        for text in texts:
            terms = set(self._tokenize(text, self.ngram_range))
            for t in terms:
                df_counter[t] += 1

        # Filter by min_df, rank by df
        valid = [(t, df) for t, df in df_counter.items() if df >= self.min_df]
        valid.sort(key=lambda x: -x[1])
        top = valid[: self.max_features]

        self.vocab_ = {t: i for i, (t, _) in enumerate(top)}
        self.idf_ = {t: math.log((n + 1) / (df + 1)) + 1 for t, df in top}
        return self

    def transform(self, texts: list[str]) -> list[list[float]]:
        rows = []
        for text in texts:
            vec = [0.0] * len(self.vocab_)
            term_freq: Counter = Counter(self._tokenize(text, self.ngram_range))
            total = sum(term_freq.values()) or 1
            for term, count in term_freq.items():
                if term in self.vocab_:
                    tf = count / total
                    vec[self.vocab_[term]] = tf * self.idf_[term]
            rows.append(vec)
        return rows

    def get_feature_names(self) -> list[str]:
        return [t for t, _ in sorted(self.vocab_.items(), key=lambda x: x[1])]


# ──────────────────────────────────────────────────────────────────────────────
# DATA LOADING
# ──────────────────────────────────────────────────────────────────────────────

def load_split(csv_path: Path) -> tuple[list[dict], list[int]]:
    rows, labels = [], []
    with open(csv_path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            rows.append(row)
            labels.append(1 if row["compliance_status"].strip() == "non_compliant" else 0)
    return rows, labels


def build_family_encoder(rows: list[dict]) -> dict[str, int]:
    families = sorted({r["control_family"].strip() for r in rows})
    return {f: i for i, f in enumerate(families)}


def extract_features(rows: list[dict], tfidf: SimpleTfidf,
                     family_enc: dict[str, int],
                     n_families: int) -> list[list[float]]:
    tfidf_mat = tfidf.transform([r["log_message"] for r in rows])
    result = []
    for i, row in enumerate(rows):
        vec = list(tfidf_mat[i])  # TF-IDF features

        # Numeric features
        for feat in NUMERIC_FEATURES:
            try:
                vec.append(float(row.get(feat, 0)))
            except (ValueError, TypeError):
                vec.append(0.0)

        # One-hot control_family
        fam_vec = [0.0] * n_families
        fam_idx = family_enc.get(row["control_family"].strip(), -1)
        if fam_idx >= 0:
            fam_vec[fam_idx] = 1.0
        vec.extend(fam_vec)

        result.append(vec)
    return result


# ──────────────────────────────────────────────────────────────────────────────
# PURE-PYTHON DECISION TREE (gradient boosting via sklearn if available,
# else fall back to a simple sklearn import path)
# ──────────────────────────────────────────────────────────────────────────────

def import_xgboost():
    try:
        import xgboost as xgb
        from sklearn.model_selection import StratifiedKFold, cross_val_score
        from sklearn.metrics import f1_score, confusion_matrix, classification_report
        return xgb, StratifiedKFold, cross_val_score, f1_score, confusion_matrix, classification_report
    except ImportError:
        raise RuntimeError("xgboost or scikit-learn not installed in venv. "
                           "Run: pip install xgboost scikit-learn")


# ──────────────────────────────────────────────────────────────────────────────
# CONFIDENCE INTERVAL (Wilson)
# ──────────────────────────────────────────────────────────────────────────────

def wilson_ci(p: float, n: int, z: float = 1.96) -> tuple[float, float]:
    if n == 0:
        return (0.0, 0.0)
    denom = 1 + z**2 / n
    center = (p + z**2 / (2 * n)) / denom
    margin = z * math.sqrt(p * (1 - p) / n + z**2 / (4 * n**2)) / denom
    return (max(0.0, center - margin), min(1.0, center + margin))


# ──────────────────────────────────────────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────────────────────────────────────────

def main():
    xgb, StratifiedKFold, cross_val_score, f1_score, confusion_matrix, classification_report = import_xgboost()
    import numpy as np

    print("=" * 70)
    print("  PHASE 1 — XGBoost v2 Clean Retraining")
    print(f"  Data: {DATA_DIR}")
    print(f"  Seed: {RANDOM_SEED} | Folds: {N_FOLDS} | TF-IDF: {TFIDF_MAX_FEATURES} features")
    print("=" * 70)

    # ── Load data ─────────────────────────────────────────────────────────────
    print("\n[1/6] Loading data...")
    train_rows, y_train_list = load_split(DATA_DIR / "compliance_events_train.csv")
    val_rows,   y_val_list   = load_split(DATA_DIR / "compliance_events_val.csv")
    test_rows,  y_test_list  = load_split(DATA_DIR / "compliance_events_test.csv")

    print(f"  Train: {len(train_rows):,}  Val: {len(val_rows):,}  Test: {len(test_rows):,}")
    c = Counter(y_train_list)
    print(f"  Train label dist: compliant={c[0]:,}  non_compliant={c[1]:,}  ratio={c[0]/c[1]:.2f}:1")

    # ── TF-IDF fit ─────────────────────────────────────────────────────────────
    print("\n[2/6] Fitting TF-IDF on training log_messages...")
    tfidf = SimpleTfidf(max_features=TFIDF_MAX_FEATURES, ngram_range=(1, 2), min_df=2)
    tfidf.fit([r["log_message"] for r in train_rows])
    top_terms = tfidf.get_feature_names()[:10]
    print(f"  Top TF-IDF terms: {top_terms}")

    # ── Family encoder ─────────────────────────────────────────────────────────
    family_enc = build_family_encoder(train_rows)
    n_families = len(family_enc)
    print(f"  Control families: {n_families} — {list(family_enc.keys())}")

    # ── Feature extraction ─────────────────────────────────────────────────────
    print("\n[3/6] Extracting features...")
    X_train = np.array(extract_features(train_rows, tfidf, family_enc, n_families), dtype=np.float32)
    X_val   = np.array(extract_features(val_rows,   tfidf, family_enc, n_families), dtype=np.float32)
    X_test  = np.array(extract_features(test_rows,  tfidf, family_enc, n_families), dtype=np.float32)
    y_train = np.array(y_train_list)
    y_val   = np.array(y_val_list)
    y_test  = np.array(y_test_list)

    n_features = X_train.shape[1]
    feature_names = (
        [f"tfidf_{t}" for t in tfidf.get_feature_names()] +
        NUMERIC_FEATURES +
        [f"family_{f}" for f in sorted(family_enc, key=family_enc.get)]
    )
    print(f"  Feature matrix shape: {X_train.shape}  ({n_features} features total)")
    print(f"  Breakdown: {TFIDF_MAX_FEATURES} TF-IDF + {len(NUMERIC_FEATURES)} numeric + {n_families} family one-hot")

    # ── XGBoost model ─────────────────────────────────────────────────────────
    scale_pos = sum(y_train == 0) / max(sum(y_train == 1), 1)
    model = xgb.XGBClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        min_child_weight=3,
        gamma=0.1,
        reg_alpha=0.1,
        reg_lambda=1.0,
        scale_pos_weight=round(scale_pos, 2),
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=RANDOM_SEED,
        n_jobs=-1,
        verbosity=0,
    )

    # ── 5-fold cross-validation ────────────────────────────────────────────────
    print(f"\n[4/6] Running {N_FOLDS}-fold stratified cross-validation...")
    skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=RANDOM_SEED)
    cv_scores = cross_val_score(model, X_train, y_train, cv=skf,
                                scoring="f1", n_jobs=-1)

    cv_mean = cv_scores.mean()
    cv_std  = cv_scores.std()
    cv_lo, cv_hi = wilson_ci(cv_mean, len(y_train) // N_FOLDS * (N_FOLDS - 1))

    print(f"  CV F1 scores: {[round(s, 4) for s in cv_scores]}")
    print(f"  Mean F1: {cv_mean:.4f}  ± {cv_std:.4f}")
    print(f"  Wilson 95% CI: [{cv_lo:.4f}, {cv_hi:.4f}]")

    # ── Train final model ──────────────────────────────────────────────────────
    print("\n[5/6] Training final model on full training set...")
    t0 = time.time()
    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        verbose=False,
    )
    train_time = time.time() - t0
    print(f"  Training time: {train_time:.2f}s")

    # ── Evaluation ────────────────────────────────────────────────────────────
    print("\n[6/6] Evaluating on held-out test set...")
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    overall_f1  = f1_score(y_test, y_pred, average="binary")
    overall_acc = (y_pred == y_test).mean()
    cm = confusion_matrix(y_test, y_pred).tolist()

    print(f"\n  Test accuracy : {overall_acc:.4f}")
    print(f"  Test F1 (binary): {overall_f1:.4f}")
    print(f"\n  Confusion matrix (TN FP / FN TP):")
    print(f"    {cm[0]}")
    print(f"    {cm[1]}")

    # ── Per-family F1 ──────────────────────────────────────────────────────────
    print("\n  Per-control-family F1:")
    family_results = []
    for fam, fam_idx in sorted(family_enc.items(), key=lambda x: x[0]):
        # find test rows for this family
        mask = np.array([r["control_family"].strip() == fam for r in test_rows])
        if mask.sum() == 0:
            continue
        y_true_fam = y_test[mask]
        y_pred_fam = y_pred[mask]
        n = int(mask.sum())
        if len(np.unique(y_true_fam)) < 2:
            f1_fam = float("nan")
            ci = (float("nan"), float("nan"))
        else:
            f1_fam = f1_score(y_true_fam, y_pred_fam, average="binary")
            ci = wilson_ci(f1_fam, n)
        acc_fam = (y_pred_fam == y_true_fam).mean()
        print(f"    {fam:<45} n={n:5d}  F1={f1_fam:.4f}  "
              f"CI=[{ci[0]:.4f},{ci[1]:.4f}]  Acc={acc_fam:.4f}")
        family_results.append({
            "family": fam,
            "n_test_samples": n,
            "f1_binary": round(f1_fam, 4) if not math.isnan(f1_fam) else None,
            "accuracy": round(acc_fam, 4),
            "wilson_ci_95": [round(ci[0], 4), round(ci[1], 4)],
        })

    macro_f1 = np.nanmean([r["f1_binary"] for r in family_results if r["f1_binary"] is not None])
    print(f"\n  Macro-F1 across families: {macro_f1:.4f}")

    # ── Feature importance ────────────────────────────────────────────────────
    importances = model.feature_importances_
    top_n = 15
    top_idx = np.argsort(importances)[::-1][:top_n]
    print(f"\n  Top {top_n} feature importances:")
    for rank, idx in enumerate(top_idx, 1):
        name = feature_names[idx] if idx < len(feature_names) else f"feat_{idx}"
        print(f"    {rank:2d}. {name:<40} {importances[idx]:.4f}")

    # ── Save model artifacts ──────────────────────────────────────────────────
    print("\n  Saving model artifacts...")
    with open(MODEL_DIR / "xgboost_v2.pkl", "wb") as f:
        pickle.dump(model, f)
    with open(MODEL_DIR / "tfidf_vectorizer.pkl", "wb") as f:
        pickle.dump(tfidf, f)
    with open(MODEL_DIR / "family_encoder.pkl", "wb") as f:
        pickle.dump(family_enc, f)

    metadata = {
        "training_date": datetime.now().isoformat(),
        "data_version": "v2_leakage_free",
        "random_seed": RANDOM_SEED,
        "n_train": len(train_rows),
        "n_val": len(val_rows),
        "n_test": len(test_rows),
        "n_features": n_features,
        "feature_breakdown": {
            "tfidf": TFIDF_MAX_FEATURES,
            "numeric": len(NUMERIC_FEATURES),
            "one_hot_family": n_families,
        },
        "excluded_features": sorted(LEAKY_FEATURES),
        "hyperparameters": {
            "n_estimators": 200,
            "max_depth": 6,
            "learning_rate": 0.05,
            "subsample": 0.8,
            "colsample_bytree": 0.8,
            "min_child_weight": 3,
            "gamma": 0.1,
            "reg_alpha": 0.1,
            "reg_lambda": 1.0,
            "scale_pos_weight": round(scale_pos, 2),
            "objective": "binary:logistic",
        },
        "cross_validation": {
            "n_folds": N_FOLDS,
            "mean_f1": round(cv_mean, 4),
            "std_f1":  round(cv_std, 4),
            "fold_scores": [round(s, 4) for s in cv_scores.tolist()],
            "wilson_ci_95": [round(cv_lo, 4), round(cv_hi, 4)],
        },
        "test_metrics": {
            "accuracy": round(overall_acc, 4),
            "f1_binary": round(overall_f1, 4),
            "macro_f1_across_families": round(macro_f1, 4),
            "confusion_matrix_tn_fp_fn_tp": cm,
        },
    }
    (MODEL_DIR / "model_metadata.json").write_text(json.dumps(metadata, indent=2))
    print(f"  [OK] Model metadata: {MODEL_DIR / 'model_metadata.json'}")

    # ── Save reports ──────────────────────────────────────────────────────────
    cv_report = {
        "generated_at": datetime.now().isoformat(),
        "model": "XGBoost v2 (leakage-free)",
        **metadata["cross_validation"],
        "test_accuracy": round(overall_acc, 4),
        "test_f1": round(overall_f1, 4),
    }
    (REPORTS_DIR / "xgboost_cv_summary.json").write_text(json.dumps(cv_report, indent=2))

    # Per-family CSV
    with open(REPORTS_DIR / "xgboost_per_family_f1.csv", "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["family", "n_test_samples", "f1_binary",
                                                "accuracy", "wilson_ci_95_lo", "wilson_ci_95_hi"])
        writer.writeheader()
        for r in family_results:
            ci = r["wilson_ci_95"]
            writer.writerow({
                "family": r["family"],
                "n_test_samples": r["n_test_samples"],
                "f1_binary": r["f1_binary"],
                "accuracy": r["accuracy"],
                "wilson_ci_95_lo": ci[0],
                "wilson_ci_95_hi": ci[1],
            })

    cm_report = {
        "generated_at": datetime.now().isoformat(),
        "labels": ["compliant (0)", "non_compliant (1)"],
        "confusion_matrix": cm,
        "interpretation": "Rows=actual, Cols=predicted. [0][0]=TN, [0][1]=FP, [1][0]=FN, [1][1]=TP",
    }
    (REPORTS_DIR / "xgboost_confusion_matrix.json").write_text(json.dumps(cm_report, indent=2))

    print(f"  [OK] CV summary:     {REPORTS_DIR / 'xgboost_cv_summary.json'}")
    print(f"  [OK] Per-family F1:  {REPORTS_DIR / 'xgboost_per_family_f1.csv'}")
    print(f"  [OK] Confusion matrix: {REPORTS_DIR / 'xgboost_confusion_matrix.json'}")

    print("\n" + "=" * 70)
    print(f"  PHASE 1 COMPLETE")
    print(f"  CV F1: {cv_mean:.4f} ± {cv_std:.4f}  |  Test F1: {overall_f1:.4f}  |  Test Acc: {overall_acc:.4f}")
    print(f"  Macro-F1 (per family): {macro_f1:.4f}")
    print("=" * 70)

    return metadata


if __name__ == "__main__":
    main()
